version: '3.9'
services:
  web:
    image: kaskus-next:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      kaskus:
        aliases:
          - kaskusnext

  web-dev:
    image: kaskus-next:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    command: pnpm dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      kaskus:
        aliases:
          - kaskusnext

networks:
  kaskus:
    name: kaskus
    external: true
