import type { NextPage } from 'next'
import Head from 'next/head'
import HotThreadCard from 'components/card/thread'
import HotTopics from 'components/widget/hotTopic'
import CommunitySection from 'components/widget/communitySection'
import ThreadRecomendationSection from 'components/widget/threadRecomendationSection'
import CommunityWidget from 'components/widget/community'
import CreatorSection from 'components/widget/creatorSection'
import Icon from 'components/common/icon'
import {
  KomunitasPopuler,
  ThreadrecomendationItem,
  cardItem,
  newCommunity,
  myCommunity,
} from '../services/_mock'
import { useCreatorMock } from '../services/kreator'
import { CardDisplayType } from 'types/hotThread'

const Home: NextPage = () => {
  const { data, isLoading } = useCreatorMock()

  return (
    <>
      <Head>
        <title>Kaskus</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-screen-md">
        <div className="mb-4">
          <CommunitySection
            title={KomunitasPopuler.title}
            items={KomunitasPopuler.items}
          />
        </div>
        <div className="mb-4">
          <HotThreadCard
            item={cardItem}
            displayType={CardDisplayType.THUMBNAIL}
          />
        </div>
        <div className="mb-4">
          <ThreadRecomendationSection items={ThreadrecomendationItem} />
        </div>
        <div className="mb-4">
          <HotTopics />
        </div>
        <div className="mb-4">
          <CommunityWidget
            variant={newCommunity.variant}
            items={newCommunity.items}
          />
        </div>
        <div className="mb-4">
          <CommunityWidget
            items={myCommunity.items}
            variant={myCommunity.variant}
            seeAllButton={myCommunity.seeAllButton}
          />
        </div>
        {!isLoading && data && (
          <div className="mb-4">
            <CreatorSection items={data} />
          </div>
        )}
        <div className="mb-4 p-5 text-red dark:text-red-night">
          <Icon variant="star"></Icon>
        </div>
      </main>
    </>
  )
}

export default Home
